### ISSUE TITLE
Modify build copyright/discliamer

### ISSUE THREAD

**Issue by conorbmurphy** [databricks-edu/build-tooling#45]
Modify the last cell of our builds with this disclaimer about data usage:

`%md-sandbox
&copy; 2018 Databricks, Inc. All rights reserved.<br/>
<br/>
Apache, Apache Spark, Spark and the Spark logo are trademarks of the <a href="http://www.apache.org/">Apache Software Foundation</a>.<br/>  
The data made available in this notebook may only be used for the course it was provided during and for no other purpose.<br/>

<a href="https://databricks.com/privacy-policy">Privacy Policy</a> | <a href="https://databricks.com/terms-of-use">Terms of Use</a> | <a href="http://help.databricks.com/">Support</a>`

**Comment by conorbmurphy** [comment]
@bmc

**Comment by bmc** [comment]
Done awhile ago.
