### ISSUE TITLE
Ability to parse TODO cells

### ISSUE THREAD

**Issue by conorbmurphy** [databricks-edu/build-tooling#46]
We should be able to hit "Run All" on a source notebook to make sure that it runs end to end.  We can't do this right now because we're using the format `yourDF = <<TODO>>`, which will throw an error.  It would be nice to be able write something like `# yourDF = <<TODO>>` and have the masterparse take the `#` out.  That way we can test the whole notebook with tests

@bmc

**Comment by bmc** [comment]
Fixed by runnable to-do cells awhile ago.
