### ISSUE TITLE
Reduce size of Databricks Academy logo in notebook header

### ISSUE THREAD

**Issue by markroepkedb** [databricks-edu/build-tooling#6]
Could we reduce the size of the Databricks Academy logo that heads every notebook? It's currently very large is distracting for lesson-level notebooks.

![Screen Shot 2020-05-21 at 11 01 57 AM](https://user-images.githubusercontent.com/55463913/82928644-75c0ef80-9f50-11ea-9bab-c2706271750a.png)

**Comment by joshuacook** [comment]
https://github.com/databricks-edu/build-tooling/commit/4641aee1fc4e4aef51fadb697401592cf607921e
