### ISSUE TITLE
Generate index.html for instructor notes.

### ISSUE THREAD

**Issue by SireInsectus** [databricks-edu/build-tooling#75]
Automatically generated instructor notes are AWESOME! But I forgot the need to manually generate the index page for those.

Specs:
* File name: *index.html*
* Location: Derive it from the build.yaml entry *instructor_notes*. In this case it would be the parent of whatever is specified here.
* The HTML & H1 title can be the course's name + "Instructor Notes"
* For each uploadable and buildable file in the build.yaml create one entry in a bulleted list and just assume that there will be a resulting *.html file for that notebook - broken links for notebooks without instructor notes are not an issue here.

Here are two examples:
* https://files.training.databricks.com/courses/ilt/Cert-Prep-Course/Cert-Prep-Course-0.3.0/amazon/instructor-notes/index.html
* https://files.training.databricks.com/courses/ilt/Spark-ILT/Spark-ILT-4.0.0/amazon/instructor-notes/index.html

For context, you can see how they are used here:
https://files.training.databricks.com/courses/ilt

**Comment by bmc** [comment]
Added to `bdc` version 1.34.0.
