### ISSUE TITLE
New feature to tag the git repo with a course's name and version

### ISSUE THREAD

**Issue by SireInsectus** [databricks-edu/build-tooling#78]
Something along the lines `bdc --tag` and `course tag` that uses the build.yaml to get the course's name (not title) and version to create a tag and apply it to git.

**Comment by bmc** [comment]
I'll get to this one on the next round of enhancements. `git` tends to run slowly inside the docker containers. I'd like to figure out how to speed that up. (Increasing system resources given to Docker might be one solution. See https://stackoverflow.com/questions/53831687/git-goes-too-slow-in-docker-container, for instance.)

Until I can reliably get `git` to be less slow from within Docker, I want to hold off adding this feature.

**Comment by bmc** [comment]
Okay, this seems to perform fine for me, so I've added it.

**Comment by bmc** [comment]
`bdc --tag /path/to/build.yaml` or `course tag`.
