### ISSUE TITLE
Breaks if tmp directory is a symlink

### ISSUE THREAD

**Issue by dougbateman** [databricks-edu/build-tooling#81]
FileNotFoundError: [Errno 2] No such file or directory: '/Users/dougbateman/tmp/curriculum'
doug:training$ ls -F ~/tmp
/Users/dougbateman/tmp@

**Comment by bmc** [comment]
Where is the symlink pointing? If it's pointing to a path that is not pushed into the Docker container, then, yeah, it'll fail. The aliases mount your home directory into the docker container. That's it. If you refer to a path that is symlinked to something _outside_ your home directory, then the symlink is pointing to something that isn't visible inside the Docker container.

I'm closing this one. User error. :-)
