### ISSUE TITLE
'course diff' hangs

### ISSUE THREAD

**Issue by dougbateman** [databricks-edu/build-tooling#82]
doug:~$ course status
+ cd /Users/dougbateman/repos/training
+ git status
<hangs>

**Comment by dougbateman** [comment]
Both 'course diff' and 'course status' hang.

**Comment by dougbateman** [comment]
'course diff' is also oddly running 'git status' instead of 'git diff'

**Comment by bmc** [comment]
`course diff` now invokes `git diff`. The hang only occurs when `course` runs in Docker, and it's not really hanging. It's just slow. It's a function of running `git` within the Docker container. I just ran `git` manually inside the Docker container, and it is _slow_. But it does eventually complete.

There are suggestions that beefing up the resources allocated to Docker might help. See https://stackoverflow.com/questions/53831687/git-goes-too-slow-in-docker-container
