### ISSUE TITLE
Change WARNING message for skipped files

### ISSUE THREAD

**Issue by SireInsectus** [databricks-edu/build-tooling#83]
The error reads "WARNING: These files from /Curriculum/Structured-Streaming aren't in the build file and were not copied."

These files are actually in the build file but are being skipped. Because this isn't even a warning, but an 100% intentional behavior, I'm suggesting that the output be more along the lines of this:
```
"SS 05 - Using Event Hubs.scala" -> SKIPPED
```
as in
```
"SS 04 - Using Kafka.scala" -> /Users/jacobp/repos/training/modules/Self-Paced/Structured-Streaming/04-Using-Kafka.scala
"Labs/SS 04 - Using Kafka Lab.scala" -> /Users/jacobp/repos/training/modules/Self-Paced/Structured-Streaming/Labs/04-Using-Kafka-Lab.scala
"SS 05 - Using Event Hubs.scala" -> SKIPPED
"Labs/SS 05 - Using Event Hubs Lab.scala" -> SKIPPED
"SS 99 - Twitter Capstone.py" -> /Users/jacobp/repos/training/modules/Self-Paced/Structured-Streaming/Labs/99-Capstone-Twitter.py
```

**Comment by bmc** [comment]
It seems there are three possibilities:

1. The files are downloaded and are in the `build.yaml`.
2. The files are downloaded and are _not_ in the `build.yaml`.
3. The files are downloaded, but are marked `skipped`.

#3 is mistakenly being treated (by `bdc` as the same as #2). I will fix.

**Comment by bmc** [comment]
Fixed. Will be released soon.
