### ISSUE TITLE
A cell tag COURSE_ONLY that takes an argument

### ISSUE THREAD

**Issue by joshuacook** [databricks-edu/build-tooling#84]
Would be useful to be able to enable or disable a block of code for a specific course e.g.

Classroom-Setup
```
%python

# COURSE_ONLY azure-data-engineering

dbutils.unmount ...
```

Then in a notebook show how to mount that same directory. Toward modular global scripts so that course specific changes are made on one file, rather than creating a classroom setup for every course.

Also useful to verify a runtime. See recent work Brooke did:

```
assert '-ml-' in sc.getConf().get('spark.databricks.clusterUsageTags.sparkVersion'), "You must use the ML Runtime to run this material."
```

is better in an init script but should only be run for ML/DL content.

**Comment by dougbateman** [comment]
Would it need to support a list of courses?  Or perhaps could it be a check for a variable that's set in a build.yaml so that more than 1 course could have it?

**Comment by joshuacook** [comment]
Either would work.

**Comment by joshuacook** [comment]
May not be entirely necessary per some later convos.

**Comment by bmc** [comment]
If this is no longer necessary, can we close it?
