### ISSUE TITLE
New feature to use the inline editing feature against the source path to build the destination path

### ISSUE THREAD

**Issue by juno-lee** [databricks-edu/build-tooling#90]

**Comment by bmc** [comment]
Can you provide an example of the substitution (or substitutions) you wish to be able to do?

**Comment by juno-lee** [comment]
Here's an example of how `src` and `dest` are written for a certifications notebook with the current version:
  - src: "Challenges/Readers-Writers-1-Advanced-Writes/DCAD-197-Partitioned-Writes-by-Day.scala"
    dest: $target_lang/Challenges/Readers-Writers-1-Advanced-Writes/$basename.$target_extension

This is what I'd like to be able to write instead for the destination path:
    dest: $target_lang/$source_filepath.$target_extension

Being able to access the `src` filepath in `dest` would allow me to have one default `dest` path that removes many many lines from the build file for certifications. Thank you!

**Comment by bmc** [comment]
This is implemented and will be pushed soon. Slight change: You'll use `$source_path_no_ext`, just to emphasize that the source path being substituted has no extension (which means you _have_ to use `$target_ext`).

Also, this variable is _only_ available if the source path is _not_ absolute.
