### ISSUE TITLE
Support $course_id.dbc in build.yaml for `student_dbc:`

### ISSUE THREAD

**Issue by dstrodtman-db** [databricks-edu/build-tooling#93]
Enablement team is actively maintaining all builds of our courses using `${course_name}-${course_version}.dbc`, currently through renaming as a command line operation. Support here would remove one small but tedious step.

If possible, simultaneous output of a copy of this dbc as `${course_name}-latest.dbc` would remove all but the manual upload to the target s3 bucket.

Low priority ask, but much appreciated if this is simple enough to implement.

**Comment by bmc** [comment]
I've added a fix allowing substitution of `$course_name`, `$course_version` and/or `$course_id` into `student_dbc` and `instructor_dbc`. (`$course_id` expands to `${course_name}-${course_version}`).

This will be in a new release of the tools, which should happen this week.

**Comment by bmc** [comment]
Fixed and pushed.
